data:
  perbatch_cutoff: False
  perbatch_cutoff_type: random
  collate_fn_type: optimized
  train_batch_size: 16         
  micro_batch_size_per_gpu: 1  
  train_files: ~/data/gsm8k/train.parquet
  val_files: ~/data/gsm8k/test.parquet
  tokenized: False
  prompt_key: question
  response_key: answer
  max_length: 256              
  truncation: right            
  chat_template: null
  resp_cutoff_ratio: 0.0
  pad_token_id: null
model:
  partial_pretrain: ~/models/gemma-1.1-7b-it
  partial_huggingface: "Qwen/Qwen3-0.6B"
  fsdp_config:
    wrap_policy:
      min_num_params: 0
    cpu_offload: False
    offload_params: False
  external_lib: null
  enable_gradient_checkpointing: False
  trust_remote_code: False
  lora_rank: 0
  lora_alpha: 16
  target_modules: all-linear
  attention_dropout: 0.0
optim:
  lr: 1e-4                   
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.05
  clip_grad: 1.0
ulysses_sequence_parallel_size: 1
use_remove_padding: False
trainer:
  default_local_dir: /tmp/sft_model
  default_hdfs_dir: hdfs://tmp/experiments/gsm8k/gemma-1.1-7b-it/ # change the hdfs path here
  resume_huggingface: True
  resume_path: null
  resume_training: False
  project_name: gsm8k-sft
  experiment_name: test
  total_epochs: 3
  total_training_steps: null
  logger: ['console']
  seed: 1
  save_checkpoint_steps: 200
diffusion:
  token_reweighting: false  # use focal loss for token-level reweighting
  alpha: 0.25  # for focal loss
  gamma: 2  # for focal loss
  time_reweighting: original  # time-level reweighting strategy
  cart_p: 0.1
